### ISSUE TITLE
Data Privacy Issues

### ISSUE THREAD

**Issue by brightcolorfulflickers** [national-voter-file/national-voter-file#188]
# Problem

Have you considered the serious privacy issues that your project creates? Knowing someone's name, birthdate, and address could be enough to convince a company to let someone else access that person's account. This sort of data enables stalkers to track down victims who may be trying very hard to protect their home address. This sort of data could be used in online doxxing campaigns to harass marginalized individuals. I'm asking you to seriously consider how threatening this feels to people who are often targeted for harassment online and for victims of domestic violence.

**Comment by gesa** [comment]
If @slavingia's [tweet](https://twitter.com/shl/status/837449988154114049) is to be believed, you need to seriously up your documentation game. Yesterday. Talk about what restrictions will exist on the data, what actions one must take to access it, add it to the README, add it to a wiki, add it to the site. **How people are going to use your api should be planned, discussed, and written before you start working on it**

**Comment by onebree** [comment]
I'm interested in seeing what the authors of this project see as the benefit. Aside from selling trends of anything else extrapolated from the data to customers. I can only think of nefarious or privacy-breaching purposes of this project.

Is the purpose to visualize how a city, county, state voted in some election? Because I've already seen such visualizations posted on state government websites. For example, NJ showed a breakdown of red/blue percentage a few days after the 2016 election.

But that's the state handling its own data. Not a third party asking for these records to be publicly available in a single place. To pinpoint the political views of someone based on how they voted.

I don't know... I just don't see much positive outcome in this. Please explain to me what the benefits are

**Comment by slavingia** [comment]
Thanks for creating this issue. I'll respond with more information later tonight or tomorrow. For those seeking more context, a long Twitter thread bloomed from here and here: 

https://twitter.com/veganstraightedge/status/837444124445794304
https://twitter.com/gesa/status/837440220760924162

I addressed this in the Tweets, but to recap: we'll be following the restrictions of each state, as @onebree pointed out. We're not going to make _any_ records publicly available.

More coming soon! Thanks again.

**Comment by slavingia** [comment]
I've created an issue for the website where we can flesh this stuff out. Feel free to chime in there as well: https://github.com/national-voter-file/national-voter-file.github.io/issues/15

**Comment by slavingia** [comment]
We've added more context to the README and are working on the website (issue linked in previous comment) too: https://github.com/national-voter-file/national-voter-file/commit/db54f24ad3d997dca1aca137649ccaaa46494d5f
