### ISSUE TITLE
Integration tests for prepared files (post cleanup)

### ISSUE THREAD

**Issue by tanyaschlusser** [national-voter-file/national-voter-file#56]
Enforce data constraints on all relevant columns in the Python-processed voter files.  (e.g. ensure 'STATE_NAME' follows the pattern 'NY' not 'ny', 'N.Y.' or 'New York'). Exit with error and appropriate message on failure.

**Comment by mbiokyle29** [comment]
I want to tackle this! I am guessing these are tests around the `<State>Prepare.py` files in `src/main/python`?

**Comment by tanyaschlusser** [comment]
Yes, you're right! There's nothing that I'm aware of that explicitly documents any constraints for any fields. I think you need access  to the dropbox folder containing sample files, so you can actually see what's in the data that get loaded :-)

**Comment by JoeNVF** [comment]
I put some comments in the NC file outlining what some of the things are, if my tests tonight go well I should be submitting a pull request for them.

There are a few things that will need to be fixed for future integration efforts.  Right now each state has it's own prepare file and it's own ETL process, we want to simplify that so all states use the same ETL process.  To do that we need to standardize the outputs from the prepare files.

State names, Race, birthdate (already worked this issue, some states only provide age so we estimate birthdate as Jan 1st of (current year - age) and I will be adding a flag stating the birthdate is an estimate, if we later get accurate information we can update the record).

County code/County name (some states use county codes, which are specific to them) will need to be handled in the ETL.

Political parties will be a pain, as not all parties are national.  We will need to standardize them, and identify which are national (like Dem, Rep, Green, Lib) and which are state specific.  Then reflect that somehow in a party_dim (maybe id, partyName, partyAbbr, partyShortName, some how reflect state or list of states).  Also need to make sure PartyA in CA is the same as PartyB in NC.  Any finally, standardize the independent/no party/etc.  IMO Unaffiliated (UA) would be the best way to go for that, as there are some parties that use Independent.

Those are all the things I can think of, but feel free to add more if there's something else you think we need to standardize.  Remember, the end goal here is to make it easy to link data and for campaigns to grab lists of voters based off any criteria.

**Comment by JoeNVF** [comment]
Oh, forgot, voter status (Active/Inactive) is reflected differently between the states, will need to normalize that as well.  Some spell it out, and some just use A/I, need to pick one format and force that on all of them.

**Comment by mbiokyle29** [comment]
Yeah I have been trying to get my mind all the prepare files. I think the first step is to try and refactor them a bit, standardize things so that new prepare files can follow the same pattern. I'd like to lock down some set of functions that all prepare scripts need and wrap that around a class that we can abstract. I think this will facilitate testing and further development.

Sounds like if we formalize the outputs to ETL in standard way, the formalization of the prepare scripts should follow easily from there.

**Comment by JoeNVF** [comment]
The PrepareUtils file does that for some of it, but of course the input fields will always be different.  Be careful with looking for things to wrap up, as some things (like prepareDate) may do the same thing but be in a slightly different format (I use prepareDate as an example because it's different between NY and NC).

**Comment by mbiokyle29** [comment]
I have made a bit of progress on this. 
- I set up testing with `nose2`
- Added a unit test file for `NewYorkPrepare.py`, got one test in there to validate the date formatter is doing what I think it's doing
- I refactored the `NewYorkPrepare.py` script to be a bit more approachable from a testing perspective. I think that may be the way to go instead of getting crazy with the class approach.
- I also started a small framework for integration testing. I think generally we should be able to set up an input file for each prepare script and then the running, and validation should be the same for all files (I think?)

What is the go to reference for "what" the prepared data looks like? So I can actually write up the validators?

**Comment by tanyaschlusser** [comment]
Yay +1 nose2!
I think the google doc I'm working on is the current 'go to reference' but it leaves much to be desired and should get input (please :-) 
https://docs.google.com/spreadsheets/d/1TcxEItYyThV9l6IK5xfdOCgXsGUkiBO-ecqJ078viog

**Comment by tanyaschlusser** [comment]
Agree!
